### ISSUE TITLE
Unable to add new lines to table after a single new line is added with saving disabled

### ISSUE THREAD

**Issue by fataldarkness** [ondutysoftwaresolutions/oddatatable#4]
### Problem Description:
When you have a table with saving disabled and try to add a row to it, the add button becomes disabled. The add button is never reenabled and  the user is then unable to add additional rows.

### Use case:
I have a use case where a user needs to build out a table of products. This requires entering in multiple new product lines. The product lines are taken into the screen flow for further processing once the user is done. This processing must be done before the product lines are written to the database so I cannot use saving.

### Steps to Reproduce:

1. Create a screen flow with the On Duty Data Table component on a screen
2. Configure the table with an object, a few columns. Ensure adding is enabled and saving is disabled.
3. Save and debug or run the flow
4. Attempt to add a new row. Note that the add button becomes disabled.
5. Note there are no controls or indication to the user on how to add additional rows.

### Suspected Cause:
I suspect this is related to Release 1.3.0, specifically this change: "Disable buttons when editing and need to save" where the need to save is incorrectly determined if saving is disabled.

<img width="294" alt="image" src="https://github.com/user-attachments/assets/02b043b3-c37d-4b61-83e8-da6b53b63404">

<img width="757" alt="image" src="https://github.com/user-attachments/assets/efd7dbab-7736-4c3d-b2ac-bc6dd8bebc77">

**Comment by fataldarkness** [comment]
Likely this issue was introduced pretty much anywhere where disabled={hasChanges} was added in commit #7c68980.

Not gonna presume how to work on your application as I am more admin then dev and you likely know best, however I'd consider replacing that with a different boolean called "savingRequired" or similar that returns the value of hasChanges unless saving is disabled would likely fix this issue.

**Comment by engPabloMartinez** [comment]
hey... good spot... yeah this was introduced there as you said.
I will have a look and release an update pretty soon.

**Comment by engPabloMartinez** [comment]
Hi @fataldarkness this fix will be included in the next release, which it will be as soon as I finish a couple of other bugs I have encountered.

Cheers

**Comment by fataldarkness** [comment]
@engPabloMartinez Thanks man, this is a pretty cool component that I can see myself using quite a bit. Will keep my eyes out for that release!

**Comment by engPabloMartinez** [comment]
This bug is fixed in the latest release.
https://github.com/ondutysoftwaresolutions/oddatatable/releases/tag/1.3.1
