### ISSUE TITLE
Component Width Issue in Modal

### ISSUE THREAD

**Issue by the-brittanie** [ondutysoftwaresolutions/oddatatable#5]
Hello! We are using the component for some inline editing and noticed when we use it in a flow that is launched from a modal, once the flow reaches that table screen the width of all tables/components after is set left justified in the modal.  My guess is the css is being set at one point for the table and never reset at the end?  Any help would be greatly appreciated!

![image](https://github.com/user-attachments/assets/a0aceaad-2f17-4a88-a2e1-1cd52f62cf13)

**Comment by engPabloMartinez** [comment]
Hi there, I never seen this behaviour. The table should take all the width
available.

Is it not inside a 2 column section?
Is it inside experience cloud? As sometimes EC mess up with CSS.

If neither, can you screen shot the columns configuration popup? You can
cross out the field names if you want, labels too.

Cheers

Pablo Martinez

Founder

On Duty Software Solutions
64 22 460 36 19
***@***.***
Linkedin <https://www.linkedin.com/in/ingpablomartinez/>

**Comment by the-brittanie** [comment]
Hi, it's not in EC, just our dev sandboxes.  Here is the popup:
![image](https://github.com/user-attachments/assets/71594e9f-39de-4844-a22e-451316423484)

**Comment by engPabloMartinez** [comment]
Thanks, yeah I cannot replicate that behaviour with same configuration.

I am guessing this was added inside a Flow section with 2 or more columns.

But that is a guess. That config with the table should take all the
available space.


Pablo Martinez

Founder

On Duty Software Solutions
64 22 460 36 19
***@***.***
Linkedin <https://www.linkedin.com/in/ingpablomartinez/>

**Comment by the-brittanie** [comment]
Thanks, Pablo! I found the issue - it was with the modal component and not the table component. Thanks for your help!
